/*
 * This file is generated by jOOQ.
*/
package com.reservation.jooq;


import com.reservation.jooq.tables.Reservation;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Study extends SchemaImpl {

    private static final long serialVersionUID = 1606844236;

    /**
     * The reference instance of <code>study</code>
     */
    public static final Study STUDY = new Study();

    /**
     * The table <code>study.reservation</code>.
     */
    public final Reservation RESERVATION = com.reservation.jooq.tables.Reservation.RESERVATION;

    /**
     * No further instances allowed
     */
    private Study() {
        super("study", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Reservation.RESERVATION);
    }
}
