/*
 * This file is generated by jOOQ.
*/
package com.reservation.jooq;


import com.reservation.jooq.tables.Reservation;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in study
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>study.reservation</code>.
     */
    public static final Reservation RESERVATION = com.reservation.jooq.tables.Reservation.RESERVATION;
}
